### ISSUE TITLE
flameshot doesn't work in sway

### ISSUE THREAD

**Issue by leozhang1** [flameshot-org/flameshot-org.github.io#101]
when I type "flameshot gui", it just hangs. I tried this link: https://github.com/flameshot-org/flameshot/blob/master/docs/Sway%20and%20wlroots%20support.md
but it didn't work :/ please help :' (

**Comment by mmahmoudian** [comment]
Please create an issue for one problem in only one repo. What you have done is practically spamming as you already posted this:

https://github.com/flameshot-org/flameshot/issues/2959
