### ISSUE TITLE
App download process is complicated for regular users

### ISSUE THREAD

**Issue by YevhenVo** [flameshot-org/flameshot-org.github.io#115]
Download button does not start the installer download, but redirects the user to Latest releases at GitHub. So users will see professional GitHub GUI for programmers with redundant information that is difficult for them to understand. It will be difficult for the user to understand which file to download.

To make it easier for regular users to download the product, you can consider creating a single download button with a direct link to the latest version of the program.

The suggestions below are made in order to improve the user experience and attract new users to the product.

1. Make one button with direct link to installer with latest release.

2. Make one Download button instead of a few.

![image](https://user-images.githubusercontent.com/47913521/222907191-1c8793fd-8bba-4055-8ad4-54b1e2c22c41.png)

3. Name it "Download".

4. All alternative ways to install app and installers put below like link. Similar to "Looking for older releases?"
So "Install via Homebrew" will become link instead button. This method is for advanced users, so they will find link and know what to do next.

If it's important to keep this link like button, than switch it with "Download". Most of regular users looking for it, not for Homebrew installation.

5. Same for Windows OS.
"Download" button. Link for Portable version.
 
![image](https://user-images.githubusercontent.com/47913521/222908350-5d5f82b3-40fd-449e-a9a8-b46bcc1a2102.png)

6. Add some comments what is portable and what it for. Ex: "Run and use Flameshot without installation on computer. You can copy app file to USB flash drive (or any local drive), take it with you and use where you need it. For example you can use it on computers without installed Flameshot if installation of software is prohibited.

7. Similar for Linux.

![image](https://user-images.githubusercontent.com/47913521/222910825-d8052b63-2e82-4f61-930c-4718061f1be1.png)

Change Button for Nightly-bilds to link.

Section "Install via Package Manager" better put right below Snap Store and Flathub buttons.

Put link for for Nightly-bilds below. Regular users don't use it, pro users will find it there.

Would be great if terminal commands will look like terminal and copy button will be near. Ex:

![image](https://user-images.githubusercontent.com/47913521/222913557-f8b151db-5633-46ae-a2a1-9ebff25575ff.png)

_source_: https://docs.requarks.io/install/ubuntu

9. It is better for the site to define OS on users gadget itself and put proper link on button was for users OS.

I would be happy to work to improve the product and make it available to a wider audience.

**Comment by mmahmoudian** [comment]
Thank you for the issue but it is a duplicate. Please read this and update your suggestion so that it completely addresses all questions and concerns

https://github.com/flameshot-org/flameshot-org.github.io/issues/109


Also, I assume you are only concerned about Windows users. So you should very clearly state that in the title and the text to avoid backlash and confusion.

**Comment by YevhenVo** [comment]
> 



> Thank you for the issue but it is a duplicate. Please read this and update your suggestion so that it completely addresses all questions and concerns
> 
> #109
This issue was closed. I didn't found it.
Please tell me, I should leave comments in #109 instead this issue?
 
> Also, I assume you are only concerned about Windows users. So you should very clearly state that in the title and the text to avoid backlash and confusion.
No. Not only Windows users. There is potential to simplify the download process for users of all platforms and thus make Flameshot a more popular application.

A convenient, simple and clear process of downloading and installing the application will allow more Flameshot users to quickly install it and enjoy it.
