### ISSUE TITLE
"macOS" instead of "MacOs"

### ISSUE THREAD

**Issue by IngrownMink4** [flameshot-org/flameshot-org.github.io#53]
Hi!

This was simply to suggest changing the name "MacOs" to "macOS" on the web page.
(I know, it's stupid to open an issue for this, lol)

![Captura de pantalla de 2022-01-29 01-32-26](https://user-images.githubusercontent.com/25466522/151639420-fc1f47cf-7d5a-40f5-9a13-eaacc091914c.png)

**Comment by mmahmoudian** [comment]
It's not stupid, it always worth the effort to be correct. Thanks for reporting this👍🏼
